From the Coursera course [Neural Networks and Deep Learning](https://www.coursera.org/learn/neural-networks-deep-learning/)

Week 2 Video = [A Note on Numpy Vectors](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/87MUx/a-note-on-python-numpy-vectors)

In [3]:
import numpy as np

a = np.random.randn(5)
print(a)
print(a.T)  # Weird! A and A^T the same
print(np.dot(a, a.T)) # Even more weird we get a scalar per Andre Ng
                      # (Mathemetically that's not that weird since dot product is a scalar result)

[-0.51534142  0.82573975 -1.54399858 -0.35402755  0.25181498]
[-0.51534142  0.82573975 -1.54399858 -0.35402755  0.25181498]
3.5201008318786475


In [4]:
# Instead use as suggested by Andrew Ng

a = np.random.randn(5,1)
print(f'a = {a}')
print(f'a^T = {a.T}')
print(f'Product a * a.T= {np.dot(a, a.T)}')  #

# call assert if you need it.
assert(a.shape == (5,1)) # This will not assert
#
b = np.random.randn(10,)
print(b)

a = [[-0.58973703]
 [ 0.5257175 ]
 [ 0.65971669]
 [-0.03530906]
 [-0.18796872]]
a^T = [[-0.58973703  0.5257175   0.65971669 -0.03530906 -0.18796872]]
Product a * a.T= [[ 0.34778977 -0.31003508 -0.38905937  0.02082306  0.11085211]
 [-0.31003508  0.27637889  0.34682461 -0.01856259 -0.09881844]
 [-0.38905937  0.34682461  0.43522612 -0.02329397 -0.1240061 ]
 [ 0.02082306 -0.01856259 -0.02329397  0.00124673  0.006637  ]
 [ 0.11085211 -0.09881844 -0.1240061   0.006637    0.03533224]]
[-0.69610714  0.70087627 -0.1102445   0.32234719  0.34376222  0.23659599
  0.62856923  0.92098802 -0.51833548  0.64090774]


Start of QUIZ scratchpad

In [16]:
img = np.random.randn(32,32,3)
#print(img)

x = img.reshape(32*32*3, 1)
print(x.shape)

(3072, 1)


In [20]:
# a = np.random.randn(3,3)
# b = np.random.randn(2,1)
# c = a + b
# print (c.shape)


a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b
print (c.shape)


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [15]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,1))
print(a)
print(b)
c = a * b
print (c.shape)
print(c)

[[1 9 4]
 [8 3 9]
 [2 0 9]]
[[2]
 [2]
 [9]]
(3, 3)
[[ 2 18  8]
 [16  6 18]
 [18  0 81]]


In [21]:
a = np.array([[2,1], [1,3]])

b = np.dot(a, a)

print(b)

[[ 5  5]
 [ 5 10]]


In [24]:
a = np.array([[1,1], [1,-1]])
b = np.array([[2],[3]])

c = a + b
c

array([[3, 3],
       [4, 2]])